### ISSUE TITLE
Use this for communication

### ISSUE THREAD

**Issue by tsloughter** [erlef/eef-observability-wg#1]
Instead of a google group we should try only using this project for communication. and not end up splitting discussions. Are there any concerns about this?

**Comment by hauleth** [comment]
We should probably move all tasks from the Google Docs here and assign proper people to these.

**Comment by binaryseed** [comment]
I wonder if github's "Team Discussions" would be helpful here:

https://help.github.com/en/articles/about-team-discussions

I'm also fine using a repo / issues, just noticed that feature

**Comment by GregMefford** [comment]
I've used team discussions before - it works fine and it very much like this type of Issue discussion thread, only without showing up as an issue. It also makes it easy to organize discussions because they're at the Team level (so you can set up sub-teams as needed) instead of the Repo level (where they can clutter the actual issues that are being worked on).

**Comment by tsloughter** [comment]
I don't think we have discussions that aren't also "issues" so we can stick to using issues. If that becomes a problem we can move to team discussions. It just requires me adding everyone to the organization (can't just be repo collaborators) and I'm lazy :)

**Comment by GregMefford** [comment]
We could probably close this issue at this point, since there weren't any dissenting opinions about where we should track our tasks/communication.
